---
version: 2
jobs:
  build:
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-{{ .Branch }}-{{checksum "yarn.lock"}}
            - v1-yarn-{{ .Branch }}
            - v1-yarn-master
      - run: yarn
      - run: |
          npx jest --coverage
          bash <(curl -s https://codecov.io/bash)
      - run: {command: "npx eslint .", when: always}
      - run: {command: "npx flow check", when: always}
      - run:
          command: npx eslint .
          when: always
      - save_cache:
          key: v1-yarn-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli-engine-config/node_modules
            - /usr/local/share/.cache/yarn
